# Generated by Django 3.2.9 on 2022-05-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='tel',
            field=models.CharField(max_length=30, verbose_name='Телефонный номер'),
        ),
        migrations.AlterField(
            model_name='site',
            name='time',
            field=models.CharField(max_length=100, verbose_name='Рабочее времяxx'),
        ),
    ]
