# Generated by Django 3.2.9 on 2022-05-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20220522_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Ваше имя')),
                ('phone', models.CharField(max_length=40, verbose_name='Ваше номер')),
            ],
        ),
    ]
